### ISSUE TITLE
Zero payload size

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-sdk-go#126]
There is some problem with retrying when session token doesn't exist. It seems node starts read payload before checking session token that's why the following test fails and we can see some empty object in neofs storage (e.g. https://github.com/nspcc-dev/neofs-http-gw/issues/122).

**Note:** the problem occurs only if we uses `WithPayloadReader` option. If payload is set into the object, everything is ok.

As I see we have the options:
* Drop retrying at all (sdk)
* Reconsider node functionality to prevent read before check session token (storage node)

```
func TestZeroPayload(t *testing.T) {
	ctx := context.TODO()

	key, err := keys.NewPrivateKey()
	require.NoError(t, err)

	pb := new(pool.Builder)
	pb.AddNode("s01.neofs.devenv:8080", 1, 1)
	opts := &pool.BuilderOptions{
		Key:                     &key.PrivateKey,
		NodeConnectionTimeout:   10 * time.Second,
		NodeRequestTimeout:      3 * time.Second,
		ClientRebalanceInterval: 5 * time.Second,
		SessionExpirationEpoch:  math.MaxUint64,
	}
	p, err := pb.Build(ctx, opts)
	require.NoError(t, err)

	cnrID := cid.New()
	err = cnrID.Parse("DTf2dx9M8GJuAD9ePeKF6VaMjxBeMVko2TPSLzHkAWCN")
	require.NoError(t, err)

	content1 := "content1"
	raw := object.NewRaw()
	raw.SetOwnerID(p.OwnerID())
	raw.SetContainerID(cnrID)

        // =========================================
	// node restart here ("docker restart s01")
        // =========================================

	param := new(client.PutObjectParams).WithObject(raw.Object()).WithPayloadReader(bytes.NewBufferString(content1))
	oid, err := p.PutObject(ctx, param)
	require.NoError(t, err)

	addr := object.NewAddress()
	addr.SetContainerID(cnrID)
	addr.SetObjectID(oid)

	param2 := new(client.ObjectHeaderParams).WithAddress(addr)
	meta, err := p.GetObjectHeader(ctx, param2)
	require.NoError(t, err)
	require.Equal(t, uint64(len(content1)), meta.PayloadSize())
}

```

**Comment by alexvanin** [comment]
By design, client side streams (like `object.Put` RPC) return response after they process messages from the client. Therefore client can't process any status until it finish data transmission. Payload reader is drained before pool repeats request and here we are. 

But the reality is a bit more complicated than that. It would be bad if client had to send hundreds of megabytes over the wire until it gets an error about session token or incorrect ACL. `gRPC` actually does not send all the data over the wire if server returns an early error. Let's see what happens in our case.

## Object upload teardown

At first, SDK Client prepares parameters and sends initial message with object header, which triggers sanity checks and object transformer initialization on the server side.

Then SDK Client uses `io.Copy` to invoke `Write()`  with 3 MiB payload chunks (to fit default message size limit in `gRPC`). 
```go
_, err = io.CopyBuffer(w, r, make([]byte, chunkSize))
```

Each `Write()` creates structure with payload, signs it, and sends message to the stream.
```go
func (w *putObjectV2Writer) Write(p []byte) (int, error) {
	w.chunkPart.SetChunk(p)
	w.req.SetVerificationHeader(nil)
	if err := signature.SignServiceMessage(w.key, w.req); err != nil {
		return 0, fmt.Errorf("could not sign chunk request message: %w", err)
	}
	if err := w.stream.Write(w.req); err != nil {
		return 0, fmt.Errorf("could not send chunk request message: %w", err)
	}
	return len(p), nil
}
```

`gRPC` packs this 3 MiB payload message into http/2 data frames of smaller size to sends it over the wire. 

Asynchronously to that, server finishes sanity checks and sends an early response. At this point, `gRPC` stops transmission of the first chunk over the wire and returns `io.EOF`. Therefore:
- SDK Client chops at least 3 MiB chunk from the stream,
- some data from this chunk actually sent over the wire (I got less than 500 KiB) but then transmission dropped.

## Summary

If we are uploading the data with the size of less than 3 MiB, request retry in the pool library can upload empty object, what happens right now.

:writing_hand: ... _in progress_

**Comment by cthulhu-rider** [comment]
Bidirectional stream will break the compatibility: old servers won't send the intermediate response that heading part is OK.

I don't think that `io.Reader` reuse is legit. Does data source support some seeking (e.g. `io.ReadSeeker`)?

**Comment by alexvanin** [comment]
> Does data source support some seeking (e.g. io.ReadSeeker)?

No. In the original issue, web server, which is a data source, provides payload stream from HTTP request, which is simple `io.Reader` that piped into pool / SDK Client. This data is not buffered and can't be re-read again. 

---

One more option is to create new session token manually on each `PUT` request. It will not be atomic as well, but I think it makes much less likely that remote node will restart before `PUT` request.

The optimal solution is to handle server restart during health checks, but I am not sure there is a way to do that. Last time I looked into it, didn't find anything useful.

**Comment by alexvanin** [comment]
According to [gRPC Channel State API](https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md#channel-state-api), we technically can use `WaitForStateChange(souceState)`. This function blocks execution until state is changed from `sourceState`. In our case we can expect it changes from `READY` to `IDLE` and this can trigger session token reconfiguration. This contradicts with an abstraction from transport layer, but we can think on perspectives to use that.
