### ISSUE TITLE
Write custom JSON marshalers for SDK

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-sdk-go#173]
Currently we reuse V2 marshalers which in turn use the default protobuf implementation.
This is somewhat strange to have `{"value":"Uv38ByGCZU8WP18PmmIdcpVmx00QA3xNe7sEB9Hixkk="}` as a CID in struct instead of 
`6ay4GfhR9RgN28d5ufg63toPetkYHGcpcW7G3b7QWSek`, especially some  JSON-RPC clients.
We might consider simplifying this format, while also taking care of version.

Thoughts? @alexvanin @carpawell @cthulhu-rider @realloc

**Comment by alexvanin** [comment]
@aprasolova will be happy about that. I doubt that we need to introduce marshallers directly in SDK, though. 

If we define custom format (e.g. removing  `{"value": "xxx=="}` indent ) it should be described on a specification level, because we want to format _protobuf_ message, not SDK structures. As soon as it described in spec and supported by api-go, it can be reused from SDK the same way it is done now.

**Comment by cthulhu-rider** [comment]
Agree with @alexvanin: these helper features should be implemented at the place of use, because they diverge from the specified NeoFS platform formats.

For example, if this is command line I/O, we can define dedicated type
```
// embeds smth from NeoFS SDK Go and customizes json.Marshaler/json.Marshaler for NeoFS CLI needs.
type sessionToken struct {
  session.Token 
}
```
This approach will ensure exclusive use of the custom format, and prevent writing incompatible software.

**Comment by realloc** [comment]
I agree that we have to follow the official protobuf serialization format where possible.

**Comment by cthulhu-rider** [comment]
https://github.com/nspcc-dev/neofs-node/issues/1323
