### ISSUE TITLE
Questions re refactoring from rc2 to rc4

### ISSUE THREAD

**Issue by amlwwalker** [nspcc-dev/neofs-sdk-go#275]
Apologies for batching some questions together. I am refactoring my code to update to rc4 and have some left over bits I can't quite find the equivalents for. In each case I think a function will have just moved and it would be great if someone could point out where the function is now:

1. NeoFS `client.New()` doesn't exist anymore. What is the equivalent of:
```go
	cli, err := client.New(
		// provide private key associated with request owner
		client.WithDefaultPrivateKey(privateKey),
		// find endpoints in https://testcdn.fs.neo.org/doc/integrations/endpoints/
		client.WithURIAddress(string(network), nil),
		// check client errors in go compatible way
		client.WithNeoFSErrorParsing(),
	)
```

My guess is something like:

```go
func NewClient2(privateKey ecdsa.PrivateKey, network FS_NETWORK) {
	var c client.Client
	var prm client.PrmInit
	prm.SetDefaultPrivateKey(privateKey)
	c.Init(prm)
	var dialPrm client.PrmDial
	dialPrm.SetServerURI(string(network))
	//do I then do things like // cnrResponse, err := cli.ContainerPut(ctx, prmContainerPut) here
	//and then do I have to dial after calling ContainerPut?? Or is calling e.g cli.ContainerPut enough?
	err := c.Dial(dialPrm)
}
```
however I am not sure if/when to call `Dial` as above, and whether I need to dial at all. Previously I just could call things like ContianerPut on the client....

2. Creating session tokens for object actions.
My understanding is now session tokens have been seperated into session tokens for objects and session tokens for containers (??).
On that basis I am trying to update my functions that create the session tokens for the containers/objects. Here is my function part way through a refactor for getting an object
```go
func CreateSessionWithObjectGetContext(ctx context.Context, cli *client.Client, owner *user.ID, containerID cid.ID, expiry uint64, key ecdsa.PrivateKey) (session.Object, error) {
	var prmSessionCreate client.PrmSessionCreate
	prmSessionCreate.SetExp(expiry)
	stoken := session.Object{}
	res, err := cli.SessionCreate(ctx, prmSessionCreate)
	if err != nil {
		return stoken, err
	}
	stoken.ForVerb(session.VerbObjectGet)
	stoken.BindContainer(containerID)
	//key here
	stoken.SetAuthKey(key) //what should this be now?
	stoken.SetSessionKey(res.PublicKey())
	stoken.SetID(uuid.New())
	stoken.SetExp(expiry)
	if owner == nil {
		tmpOwner := wallet.OwnerIDFromPrivateKey(key)
		owner = &tmpOwner
	}
	//setting the owner here
	stoken.SetOwnerID(owner)

	err = stoken.Sign(key)
	if err != nil {
		return stoken, err
	}
	return stoken, nil
}
```
I am not sure how I am supposed to set the Session/Auth key now, for the session token? and also how to set the owner (which is now in the User pkg). Also, the code `res, err := cli.SessionCreate(ctx, prmSessionCreate)` still seems valid, however unused by my code, which makes me think I am missing something there too?

Am I right in thinking that now I need seperate/different session tokens if the action is on a container as opposed to an object? (but thats not true for bearer tokens?)

3. I have functions that generate unsigned session tokens so that they can be signed out of band. Similarly to above these seem to have changed, but the main part I am interested in understanding how to do now is marshalling the session token:
```go
	rawSessionToken := st.ToV2()
	binaryData, err := rawSessionToken.GetBody().StableMarshal(nil)
```
where `st` is my sessionToken I have created (but not yet signed). V2 seems to have been deprecated, so how would I sign it now?

4. Just to confirm, passing a containerID from string to object, used to be 
```go
    cntID := cid.ID{}
    cntID.Parse(str)
```
Its now
```go
    cntID := cid.ID{}
    cntID.Encode([]byte(str))
```
?

I think that should set me on my way. 

Thank you all!

System:

github.com/nspcc-dev/neofs-sdk-go v1.0.0-rc.4

Darwin AW-RD-MBP-20 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64

github.com/nspcc-dev/neofs-api-go/v2 v2.12.2

github.com/nspcc-dev/neo-go v0.98.2

**Comment by amlwwalker** [comment]
Making some progress:

I believe I can create a new client like so:

```go
//formalise the new client based on this:
//https://github.com/nspcc-dev/neofs-sdk-go/blob/3953c2166e538ec2ab5531434f019c0efec8ac33/pool/pool.go
//you can see how to wait for things (creation/deletion here too)
func NewClient(privateKey ecdsa.PrivateKey, network FS_NETWORK) (client.Client, error) {
	var c client.Client
	var prm client.PrmInit
	prm.SetDefaultPrivateKey(privateKey)
	c.Init(prm)
	var dialPrm client.PrmDial
	dialPrm.SetServerURI(string(network))
	//todo set a tieout on the dial object
	err := c.Dial(dialPrm)
	return c, err
}
```

and a session to get an object like so:

```go
func CreateSessionWithObjectGetContext(ctx context.Context, cli *client.Client, owner *user.ID, containerID cid.ID, expiry uint64, key ecdsa.PrivateKey) (session.Object, error) {
	var prmSessionCreate client.PrmSessionCreate
	prmSessionCreate.SetExp(expiry)
	stoken := session.Object{}
	res, err := cli.SessionCreate(ctx, prmSessionCreate)
	if err != nil {
		return stoken, err
	}
	stoken.ForVerb(session.VerbObjectGet)
	stoken.BindContainer(containerID)
	//key here
	stoken.SetAuthKey((*neofsecdsa.PublicKey)(&key.PublicKey))
	stoken.SetID(uuid.New())
	//todo set these
	//tok.SetExp(11)
	//tok.SetNbf(22)
	//tok.SetIat(33)
	stoken.SetExp(expiry)
	err = stoken.Sign(key)
	if err != nil {
		return stoken, err
	}
	return stoken, nil
}
```
- note - here still have the question of when/what to do with `res, err := cli.SessionCreate(ctx, prmSessionCreate)` now? when do I use that?

**Comment by cthulhu-rider** [comment]
Hey @amlwwalker nice to see you as an SDK user! At the moment the code changes and breaks a lot, but this is only for the preparation of the first release. In the future we will ensure backward compatibility.

## Client
We've changed `client` package to be the most generic.

> I believe I can create a new client like so:

Yes, that's currently the right way to open client connection to the remote NeoFS storage node, and it won't be changed. Your function `NewClient` what we leave for the implementation of applications for now, however, perhaps in the future we will provide it natively as an auxiliary function. Separating control over the client into separate steps is necessary for applications that regulate the stages of initialization, connection, etc. Btw we discussed with @alexvanin that `pool.Pool` entity can be considered as a sugared `client.Client` in some sense - it is easier to initialize, sessions are opened inside calls, etc. But for now main goal of `pool.Pool` is switching connections, and working with it in single-client mode adds costs that we have not yet accurately estimated.

## Sessions
The only thing for which the `Client.SessionCreate` now needed is the trusted object creation in remote node side: specify container, owner, user attributes, payload and here we go. To do this private session key should be allocated on server side since it's needed for object formation. In total, it makes sense to form a session through a handshake with a node only for `PUT` action.

For other actions, you do not need to contact the node directly: just fill in all the fields and sign the token.

> Am I right in thinking that now I need seperate/different session tokens if the action is on a container as opposed to an object?

Yes, object and container sessions are used in different contexts, although they are similar ideologically and structurally.

> so how would I sign it now?

Please clarify whether session tokens are signed in the runtime of your application, or is it done completely "offline"? We plan to provide the ability to override the session signature mechanism at runtime, but did not expect the need to do this outside the application. See https://github.com/nspcc-dev/neofs-sdk-go/blob/721df386c59999dd3566b9c3fa7429d944e16bff/crypto/signer.go#L46-L62

## ID encoding
All identifiers provide at most three encodings:
* string (`EncodeToString` / `DecodeString`)
* fixed-length binary (`Encode` / `Decode`)
* protobuf binary (`Marshal` / `Unmarshal`)

So old `cntID.Parse(str)` should be replaced with `cntID.DecodeString(str)`.

**Comment by amlwwalker** [comment]
Hi @cthulhu-rider 
Thanks for getting back to me - really helpful.
So just to confirm with you - would be great to check if I am doing this correctly now for `Object` session generation. I am creating helper functions to create the sessions for GET, HEAD, PUT, DELETE objects - as you say, the only one that needs `client.SessionCreate` is `PUT` - do I need to attach it to the session in anyway? Anyway is this what you would consider correct construction of object sessions:

```go
func generateSessionObject(verb session.ObjectVerb, lt acl.TokenLifetime) session.Object{
	var sToken session.Object
	sToken.ForVerb(verb)
	sToken.SetID(uuid.New())
	sToken.SetExp(lt.GetExp())
	sToken.SetNbf(lt.GetNbf())
	sToken.SetIat(lt.GetIat())
	return sToken
}
func CreateSessionWithObjectGetContext(ctx context.Context, cli *client.Client, containerID cid.ID, expiry int64, key ecdsa.PrivateKey) (session.Object, error) {
	var lt acl.TokenLifetime
	lt.SetExp(CalculateEpochsForTime(ctx, cli, expiry)) //set the token lifetime seconds
	sToken := generateSessionObject(session.VerbObjectGet, lt)
	sToken.SetAuthKey((*neofsecdsa.PublicKey)(&key.PublicKey))
	sToken.BindContainer(containerID)
	err := sToken.Sign(key)
	if err != nil {
		return sToken, err
	}
	return sToken, nil
}
func CreateSessionWithObjectHeadContext(ctx context.Context, cli *client.Client, containerID cid.ID, expiry int64, key ecdsa.PrivateKey) (session.Object, error) {
	var lt acl.TokenLifetime
	lt.SetExp(CalculateEpochsForTime(ctx, cli, expiry)) //set the token lifetime seconds
	sToken := generateSessionObject(session.VerbObjectHead, lt)
	sToken.SetAuthKey((*neofsecdsa.PublicKey)(&key.PublicKey))
	sToken.BindContainer(containerID)
	err := sToken.Sign(key)
	if err != nil {
		return sToken, err
	}
	return sToken, nil
}
func CreateSessionWithObjectPutContext(ctx context.Context, cli *client.Client, containerID cid.ID, expiry int64, key ecdsa.PrivateKey) (session.Object, error) {
	var lt acl.TokenLifetime
	lt.SetExp(CalculateEpochsForTime(ctx, cli, expiry)) //set the token lifetime seconds
	sToken := generateSessionObject(session.VerbObjectPut, lt)
	var prmSessionCreate client.PrmSessionCreate
	prmSessionCreate.SetExp(lt.GetExp())
	prmSessionCreate.UseKey(key)
	//no longer needed for anything except PUT <<---- @[cthulhu-rider](https://github.com/cthulhu-rider) here....
	//do I need to set it on sToken somehow, or just call it?
	_, err := cli.SessionCreate(ctx, prmSessionCreate)
	if err != nil {
		return sToken, err
	}
	sToken.SetAuthKey((*neofsecdsa.PublicKey)(&key.PublicKey))
	sToken.BindContainer(containerID)
	err = sToken.Sign(key)
	return sToken, err
}
func CreateSessionWithObjectDeleteContext(ctx context.Context, cli *client.Client, containerID cid.ID, expiry int64, key ecdsa.PrivateKey) (session.Object, error) {
	var lt acl.TokenLifetime
	lt.SetExp(CalculateEpochsForTime(ctx, cli, expiry)) //set the token lifetime seconds
	sToken := generateSessionObject(session.VerbObjectDelete, lt)
	sToken.SetAuthKey((*neofsecdsa.PublicKey)(&key.PublicKey))
	sToken.BindContainer(containerID)
	err := sToken.Sign(key)
	if err != nil {
		return sToken, err
	}
	return sToken, nil
}
```

**Comment by amlwwalker** [comment]
OK those scenarios make sense @cthulhu-rider thanks.
When you say "pass the public key of the party you trust" you mean whoever is making the request as opposed to the key of a storage node I assume (as i don't know how I would know the storage nodes key....)

With regards to:

```go
	create := client.PrmSessionCreate{}
	create.SetExp(lt.GetExp())
	_, err := cli.SessionCreate(ctx, create)
	if err != nil {
		return session.Container{}, err
	}
```
this is the one element I'm still not sure of - is it necessary? I don't really get it - its not attached to the session object as far as I can tell in anyway...

**Comment by cthulhu-rider** [comment]
@amlwwalker sorry for the delay in reply.

If you use `cli.SessionCreate` storage node creates a new private key (which definitely differs with node's master key) and responds with `client.ResSessionCreate` which provides `PublicKey` method to receive public key of just created private session key. This scenario is only needed for object creation.

```
	create := client.PrmSessionCreate{}
	create.SetExp(lt.GetExp())
	res, err := cli.SessionCreate(ctx, create)
	if err != nil {
		return session.Container{}, err
	}

	var pubkey neofsecdsa.PublicKey
	err = pubkey.Decode(res.PublicKey())
	if err != nil { ... }

	var token session.Container
	token.SetAuthKey(pubkey)

	// put object via client
```

For all other needs you should just receive public key of some party in any convenient way and write it into session token.

Did I understand your question correctly?

**Comment by amlwwalker** [comment]
@cthulhu-rider - this is great and a very important change in the rc4 - thank you. I have been using the request maker's public key here but the auth key needs to be the key from the client session!

and to make sure I understand, when doing anything except an object (or container???) creation, I can just use my public key in in the `SetAuthKey` field? - i.e it doesn't matter what its set to?
Thanks

**Comment by cthulhu-rider** [comment]
@amlwwalker it makes no sense to pass your own key into `SetAuthKey` - you should pass some other key. Subsequently, when providing a token, the system will consider that the operation is performed on behalf of the person specified in `SetAuthKey`. 

For example, you want me to create containers on your behalf. To do this, I send some public key `KEY_LEO` to you. You compose session token:
```
var token session.Container
token.SetAuthKey(KEY_LEO)
// set other fields
token.Sign(KEY_ALEX)
```
After that you send me the token, and I can create containers using the session:
```
var cnr container.Container
cnr.SetOwner(ALEX)
// set other fields

var prm client.PrmContainerPut
prm.SetContainer(cnr)
prm.WithinSession(TOKEN_FROM_ALEX)

var prmInit client.PrmInit
prmInit.SetDefaultPrivateKey(KEY_LEO)

var cli client.Client
cli.Init(prmInit)
// dial

_, err := cli.ContainerPut(ctx, prm)
```
So it will be your own container, but I created it using my `KEY_LEO` because you issued a power of attorney for this key.

If you do things from you person with your `KEY_ALEX`, you can just do it without a session - it's optional.

**Comment by roman-khimov** [comment]
Seems to be done to me (and rc4 is outdated now anyway).
