### ISSUE TITLE
Allow to get raw client from a pool

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#379]
Sometimes we want to have a pool, but be able to extract some client from it and use its lower-level API. Yes, it kinda defeats some of the pool's goals, but at the same time pools can be used in various ways and one of them is to get some client from time to time and work with this particular client instance, maybe we should support this.

**Comment by cthulhu-rider** [comment]
I guess the root of the problem is that the pool does not exactly implement the client interface. I don't like the idea to expose single client because this breaks complete concealment design. But I'd also completely redesign the architecture of the pool itself: base on external connection manager which can vary much from app to app. So, right now I don't mind to give single endpoint access.

**Comment by roman-khimov** [comment]
We've got #380 for some redesign.
