### ISSUE TITLE
Return errors instead of panic

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#390]
We have many places panicking on incorrect input parameters. All of them specify "Immediately panics if parameters are set incorrectly", so it's kinda legitimate to do that. Yet all of them usually return `(smth, error)`, so they might as well return errors. Returning errors is safer in general, yet some `ctx == nil` cases are a clear programmer error, so panic is justified as well (as a means to quickly give feedback during development). In some cases though parameters may be dynamic and a little less predictable, someone will miss some check that is not needed in 99% of cases, but we'll get an application crash in 1% of cases which may be frustrating for users.

Do we want to rework it or we're OK with panics?

**Comment by cthulhu-rider** [comment]
I adhere to a simple rule: errors should not cover developer errors. I still insist on panic if the developer violates the requirements. 

What I can suggest is to shift the mindfulness factor down to the source code level (compilation stage). For example:
```go
type Prm struct {
  field any
  option any
}

// REQUIRED
func (*Prm) SetField(any) {}

// OPTIONAL
func (*Prm) SetOption(any) {}

// easy to forget SetField, e.g. pass Prm{}
func Do(Prm) error {
  // panic if SetField was not called or field is incorrect because it's a programmer's mistake
}
```
is worth to be replaced with
```go
type Options struct {
  option any
}

// OPTIONAL
func (*Prm) SetOption(any) {}

// Options are options, so we can pass event Options{}
func Do(field any, options Options) error {
 // field can't be forgotten, only invalid
}
```

Again, panics are completely OK to detect developer errors. If it occurs, client should not and will not continue using this software until until the release of fixes. If it will be an error in log - the problem just hangs.

**Comment by smallhive** [comment]
I think using panic in code must require the exceptional situation. Wrong or missing argument is just an input error. The code should notify `the caller` about this, but with regular mechanism like errors.

According to [go.dev](https://go.dev/blog/defer-panic-and-recover) we have a convention about panics:
* The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values.

We are developing the `lib`. I consider we should simplify using our lib for another developers, in context of error handling and parameters passing. I see two option to achieve this:
* First is like example upper, when we should define all required parameters in func definition. But it may be not so convenient in some situations and may require many code changes.
* Second is using `the constructors` for structs. In this case we place all required args in the constructor. This leads to less mistakes from developer side to miss required parameters.

```go
type Prm struct {
  field any
  option any
}

func NewPrm(field any) Prm {
    return Prm{
        field:field,
    }
}

// OPTIONAL
func (*Prm) SetOption(any) {}

// you  can't forget to set field
func Do(Prm) error {
  // return error if `field` has wrong value
}
```
From my point of view - panic is an something unpredictable and we can't handle it in any way. Using `errors` is understandable way to describe what happened. We shouldn't try to crash users application because some developer forgot/didn't know to pass some param or fill some field in some structure.

We already using errors mechanism in struct conversion and this work perfect:
* https://github.com/nspcc-dev/neofs-sdk-go/blob/dbbb22ca28cd1f60d507c7cec35985dc5f487274/container/container.go#L51

**Comment by cthulhu-rider** [comment]
> We already using errors mechanism in struct conversion and this work perfect

yeah, because this may be a network input, not developer one

I don't like `NewPrm` because it doesn't protect from `Do(Prm{})` call like `Do(field, options{})`. It's clearer to me to accept required input as separate function parameters, although prm constructor works too ofc.

@roman-khimov thoughts? Lets sync opinions and implement final approach in `v1.0` release

**Comment by pkorotkov** [comment]
I would vote for only panicking in cases of violations of crucial invariants. IMHO, the rest of the cases, like incorrectly or partially initialized input should be expressed via `(result, err)` idiom. If, for some reason, you have to stick to an API with required settable properties at risk of ignoring by developers, you can always introduce sensible defaults for those properties.

**Comment by notimetoname** [comment]
My ideas coincide with the thoughts of [this wonderful person](https://github.com/TrueCloudLab/frostfs-sdk-go/issues/2#issuecomment-1352935876).
When i'm thinking about it, i do imagine the case when an RPC is called quite rare and kills the whole app at e.g. 3 am (it may be some rare replication, some reputation scenario, etc) without any chances to continue its work (at least partly or fully if that RPC is nothing important at all).

I tried brief googling once again for some "classic" answers on that question and i would say that with `panic` we do force making _the "true" answer_ for a user on the question "is an SDK client fatal for me?" (if use [that](https://stackoverflow.com/a/44505268) wording) and that is not smth i would expect from a lib called "SDK". So my vote is for `error` way.

**Comment by notimetoname** [comment]
> I adhere to a simple rule: errors should not cover developer errors.

@cthulhu-rider, quite a reasonable rule, i like it. But for self-made code, not an SDK, IMO.

**Comment by roman-khimov** [comment]
Thanks for all the comments. I think the consensus is that for a library (which an SDK is) `panic` is not something we should do when we can return an error, so we need to ensure this is the case.

Cases like nil passed to https://pkg.go.dev/bytes#Buffer.WriteTo are still OK to be unhandled (implicitly panicking), because it's a clear violation of the expected method use.

**Comment by smallhive** [comment]
What do you think about removing `panicMsgMissingContext` at all? I mean not replace this with something `ErrMissingContext`, but just remove this condition at all.

Context is a very common type in Go. If someone decided to put `nil` instead of real context, it would get a panic anyway (I had such experience in very begging of my Golang adventure). We shouldn't cover this mistake.

**Comment by carpawell** [comment]
@roman-khimov, @smallhive, @cthulhu-rider, was it intended not to panic ever? More than a year after this issue is closed, I see that the PR that closed it did not delete every `panic` keyword in every exported code, but just did `panic` -> `error` transition _where possible_. Just returning error where it _can be returned_ in fact. E.g. we have this: https://github.com/nspcc-dev/neofs-sdk-go/blob/1478127a209de8c9eaee40f3ee5d347f5ef1f36f/client/common.go#L33.

So the question is: should it be _possible_ to get a panic with regular user moves when this PR is closed? I thought it was not. But it is now.

**Comment by roman-khimov** [comment]
Please open a new issue.

**Comment by carpawell** [comment]
> Please open a new issue.

@roman-khimov, it was not closed correctly, why? After the PR was merged, some places were left with `panic`s.

**Comment by roman-khimov** [comment]
> Yet all of them usually return (smth, error), so they might as well return errors

We've fixed these cases. Other panics are different.
