### ISSUE TITLE
Revive `pool.Pool` tests

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#85]
## Summary
Unit tests of `pool.Pool` use mocked instance of `client.Client`, but after https://github.com/nspcc-dev/neofs-sdk-go/pull/83 its interface doesn't support mocking because of `Res` structures. We still want to test the `Pool`, but at the same time we don't want to change the `client` library because of the test.

## Task

- [x] Refactor the test and / or library so that you don't have to implement the `client.Client` interface.
- [x] Fix tests and remove `t.Skip()` calls (all places refer to current issue).

**Comment by fyrchik** [comment]
Why do `*Res` structs lack public setters?

**Comment by cthulhu-rider** [comment]
@fyrchik  because they are read-only. Do u think they should have?

**Comment by alexvanin** [comment]
With public setters we will provide more flexibility for people who would like to mock client in unit tests. To mock client now it is required to define separate client implementation (e.g. [innerring/internal/client](https://github.com/nspcc-dev/neofs-node/tree/master/pkg/innerring/internal/client)) and mock this implementation instead. With setters (and later getters for `Prm`) users will be able to mock the client without separate client implementation. 

Instead of the setters we can define constructors for `*Res`, but setters are much cleaner, IMO.

**Comment by cthulhu-rider** [comment]
I propose to postpone the solution until https://github.com/nspcc-dev/neofs-sdk-go/issues/165 is closed.
